=== gprabhu84/TAO-Assign/country.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.1">
    <xs:element name="country">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="state"/>
                <xs:element maxOccurs="unbounded" ref="Islands"/>
                <xs:element maxOccurs="unbounded" ref="Rivers"/>
                <xs:element maxOccurs="unbounded" ref="Union_Territory"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="langauage" type="xs:string"/>
            <xs:attribute name="Area" type="xs:integer"/>
            <xs:attribute name="Capital" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Rivers">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="flows_through" type="xs:IDREFS"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Islands">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="Area" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Union_Territory">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="Area" type="xs:integer"/>
            <xs:attribute name="langauage" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="subdistricts">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="rural"/>
                <xs:element ref="urban"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="urban">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="no_of_towns" type="xs:nonNegativeInteger"/>
                <xs:element ref="population"/>
                <xs:element ref="area"/>
                <xs:element ref="no_of_households"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="rural">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="no_of_villages" type="xs:nonNegativeInteger"/>
                <xs:element name="population">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="male" type="xs:nonNegativeInteger"/>
                            <xs:element name="female" type="xs:nonNegativeInteger"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element ref="area"/>
                <xs:element ref="no_of_households"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="district">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="subdistricts"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="Area" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="state">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="district"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="state_id" type="xs:ID"/>
            <xs:attribute name="Capital" type="xs:string"/>
            <xs:attribute name="language" type="xs:string"/>
            <xs:attribute name="coastal_area" type="xs:string" use="required"/>
            <xs:attribute name="neighbours" type="xs:IDREFS"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="population">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="male" type="xs:nonNegativeInteger"/>
                <xs:element name="female" type="xs:nonNegativeInteger"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="area" type="xs:float"/>
    <xs:element name="no_of_households" type="xs:nonNegativeInteger"/>
</xs:schema>

=== gprabhu84/TAO-Assign/country_IN1.xml
<?xml version="1.0" encoding="UTF-8"?>
<country xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/home/zerokelvin/OxygenXMLEditor/samples/country.xsd" name="name0" langauage="langauage0" Area="0" Capital="Capital0">
    <state name="name1" state_id="ID000" Capital="Capital1" language="language0" coastal_area="coastal_area0" neighbours="ID000">
        <district name="name2" Area="0">
            <subdistricts>
                <rural>
                    <no_of_villages>50</no_of_villages>
                    <population>
                        <male>50</male>
                        <female>50</female>
                    </population>
                    <area>0</area>
                    <no_of_households>50</no_of_households>
                </rural>
                <urban>
                    <no_of_towns>50</no_of_towns>
                    <population>
                        <male>50</male>
                        <female>50</female>
                    </population>
                    <area>0</area>
                    <no_of_households>50</no_of_households>
                </urban>
            </subdistricts>
            <subdistricts>
                <rural>
                    <no_of_villages>50</no_of_villages>
                    <population>
                        <male>50</male>
                        <female>50</female>
                    </population>
                    <area>0</area>
                    <no_of_households>50</no_of_households>
                </rural>
                <urban>
                    <no_of_towns>50</no_of_towns>
                    <population>
                        <male>50</male>
                        <female>50</female>
                    </population>
                    <area>0</area>
                    <no_of_households>50</no_of_households>
                </urban>
            </subdistricts>
        </district>
        <district name="name3" Area="0">
            <subdistricts>
                <rural>
                    <no_of_villages>50</no_of_villages>
                    <population>
                        <male>50</male>
                        <female>50</female>
                    </population>
                    <area>0</area>
                    <no_of_households>50</no_of_households>
                </rural>
                <urban>
                    <no_of_towns>50</no_of_towns>
                    <population>
                        <male>50</male>
                        <female>50</female>
                    </population>
                    <area>0</area>
                    <no_of_households>50</no_of_households>
                </urban>
            </subdistricts>
            <subdistricts>
                <rural>
                    <no_of_villages>50</no_of_villages>
                    <population>
                        <male>50</male>
                        <female>50</female>
                    </population>
                    <area>0</area>
                    <no_of_households>50</no_of_households>
                </rural>
                <urban>
                    <no_of_towns>50</no_of_towns>
                    <population>
                        <male>50</male>
                        <female>50</female>
                    </population>
                    <area>0</area>
                    <no_of_households>50</no_of_households>
                </urban>
            </subdistricts>
        </district>
    </state>
    <state name="name4" state_id="ID001" Capital="Capital2" language="language1" coastal_area="coastal_area1" neighbours="ID000">
        <district name="name5" Area="0">
            <subdistricts>
                <rural>
                    <no_of_villages>50</no_of_villages>
                    <population>
                        <male>50</male>
                        <female>50</female>
                    </population>
                    <area>0</area>
                    <no_of_households>50</no_of_households>
                </rural>
                <urban>
                    <no_of_towns>50</no_of_towns>
                    <population>
                        <male>50</male>
                        <female>50</female>
                    </population>
                    <area>0</area>
                    <no_of_households>50</no_of_households>
                </urban>
            </subdistricts>
            <subdistricts>
                <rural>
                    <no_of_villages>50</no_of_villages>
                    <population>
                        <male>50</male>
                        <female>50</female>
                    </population>
                    <area>0</area>
                    <no_of_households>50</no_of_households>
                </rural>
                <urban>
                    <no_of_towns>50</no_of_towns>
                    <population>
                        <male>50</male>
                        <female>50</female>
                    </population>
                    <area>0</area>
                    <no_of_households>50</no_of_households>
                </urban>
            </subdistricts>
        </district>
        <district name="name6" Area="0">
            <subdistricts>
                <rural>
                    <no_of_villages>50</no_of_villages>
                    <population>
                        <male>50</male>
                        <female>50</female>
                    </population>
                    <area>0</area>
                    <no_of_households>50</no_of_households>
                </rural>
                <urban>
                    <no_of_towns>50</no_of_towns>
                    <population>
                        <male>50</male>
                        <female>50</female>
                    </population>
                    <area>0</area>
                    <no_of_households>50</no_of_households>
                </urban>
            </subdistricts>
            <subdistricts>
                <rural>
                    <no_of_villages>50</no_of_villages>
                    <population>
                        <male>50</male>
                        <female>50</female>
                    </population>
                    <area>0</area>
                    <no_of_households>50</no_of_households>
                </rural>
                <urban>
                    <no_of_towns>50</no_of_towns>
                    <population>
                        <male>50</male>
                        <female>50</female>
                    </population>
                    <area>0</area>
                    <no_of_households>50</no_of_households>
                </urban>
            </subdistricts>
        </district>
    </state>
    <Islands name="name7" Area="0"/>
    <Islands name="name8" Area="0"/>
    <Rivers name="name9" flows_through="ID000"/>
    <Rivers name="name10" flows_through="ID000"/>
    <Union_Territory name="name11" Area="0" langauage="langauage1"/>
    <Union_Territory name="name12" Area="0" langauage="langauage2"/>
</country>
